version: '3.7'

services:
   mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - env/db.env
   site:
    image: cawebpublishing/caweb:centos-apache-test
    container_name: site
    depends_on:
     - mariadb
    ports:
      - "7000:80"
    restart: always
    env_file:
      - env/php.env
      - env/db.env
      - env/wp/instance.env
      - env/wp/site.env
      - env/divi/divi.env
      - env/divi/options.env
      - env/caweb/caweb.env
      - env/caweb/nav.env
      - env/caweb/options/general.env
      - env/caweb/options/utility-header.env
      - env/caweb/options/page-header.env
      - env/caweb/options/google.env
    volumes:
      - ./wordpress:/home/wp # Used if adding custom themes/plugins or if creating pages/posts
      - ./wordpress/themes:/var/www/html/wp-content/themes # Used for development
      - ./wordpress/plugins:/var/www/html/wp-content/plugins # Used for development
   phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    restart: always
    env_file:
      - env/db.env
volumes:
  db_data: